import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FBFAFE",
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    overflow: "hidden",
    backgroundColor: "#FBFAFE",
  },
  topGlow: {
    position: "absolute",
    backgroundColor: "#FFE1D2",
  },
  bottomGlow: {
    position: "absolute",
    backgroundColor: "#DDEFE2",
  },
  topBar: {
    width: "100%",
    minHeight: 58,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: "#EFEFF1",
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  scrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
  },
  content: {
    flexGrow: 1,
    alignSelf: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  illustrationContainer: {
    position: "relative",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  illustrationHalo: {
    position: "absolute",
    backgroundColor: "#FFF7F0",
  },
  lockShackle: {
    position: "absolute",
    borderColor: "#F2A23C",
    backgroundColor: "transparent",
  },
  lockBody: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF8F1",
    borderWidth: 2,
    borderColor: "#6B3C20",
    shadowColor: "#9D6136",
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  keyholeCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#6B4329",
  },
  keyholeStem: {
    width: 8,
    height: 25,
    marginTop: -3,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    backgroundColor: "#6B4329",
  },
  passwordBadge: {
    position: "absolute",
    minWidth: 92,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#FFF9F4",
    borderWidth: 2,
    borderColor: "#6D3D20",
    paddingHorizontal: 12,
  },
  passwordStars: {
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#EE9A31",
    letterSpacing: 1,
    textAlign: "center",
  },
  refreshBadge: {
    position: "absolute",
    width: 62,
    height: 62,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 31,
    backgroundColor: "#FFAA3F",
    borderWidth: 2,
    borderColor: "#6A391C",
  },
  sparkleOne: {
    position: "absolute",
  },
  sparkleTwo: {
    position: "absolute",
  },
  header: {
    width: "100%",
    alignItems: "center",
    marginBottom: 26,
  },
  title: {
    fontFamily: FONTS.bold,
    color: "#232323",
    textAlign: "center",
  },
  description: {
    maxWidth: 390,
    marginTop: 7,
    fontFamily: FONTS.regular,
    color: "#72645D",
    textAlign: "center",
  },
  form: {
    width: "100%",
  },
  phoneInput: {
    marginBottom: 6,
  },
  generalError: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: 13,
    backgroundColor: "#FFF0EA",
    borderWidth: 1,
    borderColor: "#F3C5B5",
  },
  generalErrorText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#9D3A20",
    textAlign: "right",
  },
  submitButton: {
    direction: "ltr",
    width: "100%",
    marginTop: 6,
    paddingVertical: 0,
    shadowColor: "#E66F30",
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    elevation: 7,
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#603016",
    textAlign: "center",
  },
  footer: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 72,
    paddingBottom: 4,
  },
  footerText: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#71645E",
    textAlign: "center",
  },
  loginLink: {
    minHeight: 34,
    justifyContent: "center",
    borderRadius: 7,
  },
  loginLinkText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#A94D17",
    textAlign: "center",
  },
  linkPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
});

export default styles;
