import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FBFAFE",
  },
  screen: {
    flex: 1,
    width: "100%",
    overflow: "hidden",
    backgroundColor: "#FBFAFE",
  },
  topGlow: {
    position: "absolute",
    backgroundColor: "#FFE1D2",
  },
  bottomGlow: {
    position: "absolute",
    backgroundColor: "#DDEFE2",
  },
  topBar: {
    width: "100%",
    minHeight: 58,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: "#EFEFF1",
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  scrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
  },
  content: {
    flexGrow: 1,
    alignSelf: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  illustrationContainer: {
    position: "relative",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  illustrationHalo: {
    position: "absolute",
    backgroundColor: "#FFF4EE",
  },
  shield: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#6D391B",
    backgroundColor: "#FFF6EF",
    shadowColor: "#8E5531",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 5,
  },
  shieldLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "50%",
    backgroundColor: "#FFF8F4",
  },
  shieldRight: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: "50%",
    backgroundColor: "#FFF0E8",
  },
  shieldInner: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  successCircle: {
    width: 76,
    height: 76,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 38,
    backgroundColor: "#B9E5B8",
    borderWidth: 2,
    borderColor: "#2A7E3E",
  },
  lockBadge: {
    position: "absolute",
    width: 55,
    height: 62,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  lockShackle: {
    position: "absolute",
    top: 0,
    width: 29,
    height: 31,
    borderWidth: 4,
    borderColor: "#6D391B",
    borderBottomWidth: 0,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: "transparent",
  },
  lockBody: {
    width: 52,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    backgroundColor: "#FFB557",
    borderWidth: 2,
    borderColor: "#6D391B",
  },
  sparkleOne: {
    position: "absolute",
    top: "16%",
    left: "10%",
  },
  sparkleTwo: {
    position: "absolute",
    right: "7%",
    bottom: "18%",
  },
  header: {
    width: "100%",
    alignItems: "center",
    marginBottom: 28,
  },
  title: {
    maxWidth: 410,
    fontFamily: FONTS.bold,
    color: "#232323",
    textAlign: "center",
  },
  description: {
    maxWidth: 400,
    marginTop: 8,
    fontFamily: FONTS.regular,
    color: "#72645D",
    textAlign: "center",
  },
  statusCard: {
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8BEAA",
    shadowColor: "#79675E",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  statusRow: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 12,
  },
  statusIcon: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#07882C",
  },
  statusText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 15,
    lineHeight: 24,
    color: "#302925",
    textAlign: "left",
  },
  statusDivider: {
    width: "100%",
    height: 1,
    marginVertical: 14,
    backgroundColor: "#EEE8E5",
  },
  actions: {
    width: "100%",
    marginTop: 46,
    alignItems: "center",
  },
  loginButton: {
    direction: "ltr",
    width: "100%",
    paddingVertical: 0,
    shadowColor: "#E66F30",
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    elevation: 7,
  },
  loginButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#603016",
    textAlign: "center",
  },
  homeButton: {
    minHeight: 44,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginTop: 18,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  homeButtonPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
  homeButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#A94D17",
    textAlign: "center",
  },
});

export default styles;
