import { StyleSheet } from "react-native";
import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FBFAFE",
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: "#FBFAFE",
  },
  topBar: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 20,
    color: "#24201E",
    textAlign: "center",
    writingDirection: "rtl",
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: "#EFEFF1",
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  progressArea: {
    paddingTop: 4,
    paddingBottom: 18,
  },
  progressLabels: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressTitle: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#5D5551",
    textAlign: "left",
    writingDirection: "rtl",
  },
  stepText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#FF7B32",
    textAlign: "left",
    writingDirection: "rtl",
  },
  progressTrack: {
    width: "100%",
    height: 5,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#E4E1DF",
  },
  progressFill: {
    width: "66.666%",
    height: "100%",
    alignSelf: "flex-end",
    borderRadius: 999,
    backgroundColor: "#FF8849",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: 36,
  },
  content: {
    alignSelf: "center",
  },
  sectionHeader: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    marginBottom: 18,
  },
  passwordHeader: {
    marginTop: 26,
  },
  sectionMarker: {
    width: 4,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#16833A",
  },
  sectionTitle: {
    fontFamily: FONTS.medium,
    fontSize: 17,
    color: "#16833A",
    textAlign: "left",
    writingDirection: "rtl",
  },
  fieldGroup: {
    width: "100%",
    marginBottom: 16,
  },
  inputContainer: {
    width: "100%",
    minHeight: 57,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#7E897D",
    backgroundColor: "#FBFAFE",
  },
  inputContainerError: {
    borderColor: "#C92335",
  },
  input: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: "#2F332F",
    writingDirection: "rtl",
  },
  dateFieldPressed: {
    opacity: 0.72,
  },
  dateValue: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: "#2F332F",
    textAlign: "left",
    writingDirection: "rtl",
  },
  datePlaceholder: {
    color: "#777B75",
  },
  selectText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: "#2F332F",
    textAlign: "left",
    writingDirection: "rtl",
  },
  selectPlaceholder: {
    color: "#777B75",
  },
  phoneRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  phoneInputContainer: {
    flex: 1,
  },
  countryCodeBox: {
    width: 74,
    minHeight: 57,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#7E897D",
    backgroundColor: "#FBFAFE",
  },
  countryCodeText: {
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: "#4E514D",
    textAlign: "center",
    writingDirection: "ltr",
  },
  dropdown: {
    width: "100%",
    height: 240,
    overflow: "hidden",
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D6D9D4",
    backgroundColor: "#FFFFFF",
  },
  dropdownContent: {
    flexGrow: 0,
  },
  dropdownItem: {
    minHeight: 48,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#ECEDEB",
  },
  selectedDropdownItem: {
    backgroundColor: "#F1F8F3",
  },
  dropdownItemPressed: {
    opacity: 0.65,
  },
  dropdownItemText: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: "#343834",
    textAlign: "left",
    writingDirection: "rtl",
  },
  errorText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 18,
    color: "#C92335",
    textAlign: "left",
    writingDirection: "rtl",
  },
  passwordStrengthHeader: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: -4,
    marginBottom: 8,
  },
  passwordStrengthTitle: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#4F544E",
    textAlign: "left",
    writingDirection: "rtl",
  },
  passwordStrengthLabel: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    textAlign: "left",
    writingDirection: "rtl",
  },
  passwordBars: {
    width: "100%",
    flexDirection: "row-reverse",
    gap: 5,
    marginBottom: 18,
  },
  passwordBar: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#E2E3E1",
  },
  requirements: {
    width: "100%",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 22,
  },
  requirementRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  requirementText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#50554F",
    textAlign: "left",
    writingDirection: "rtl",
  },
  checkboxRow: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginTop: 8,
    marginBottom: 16,
  },
  checkbox: {
    width: 21,
    height: 21,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#8F9990",
    backgroundColor: "#FFFFFF",
  },
  checkboxSelected: {
    borderColor: "#16833A",
    backgroundColor: "#16833A",
  },
  checkboxText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 13,
    lineHeight: 22,
    color: "#555A54",
    textAlign: "left",
    writingDirection: "rtl",
  },
  linkText: {
    fontFamily: FONTS.medium,
    color: "#FF7B32",
  },
  noticeCard: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 6,
    marginBottom: 28,
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FF8A46",
    backgroundColor: "#FFF4EC",
  },
  noticeText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#604D41",
    textAlign: "left",
    writingDirection: "rtl",
  },
  dateModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 24,
    backgroundColor: "rgba(0, 0, 0, 0.34)",
  },
  dateModalCard: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
  },
  dateModalHeader: {
    minHeight: 54,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E5E5E5",
  },
  dateModalTitle: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#292D29",
    textAlign: "center",
    writingDirection: "rtl",
  },
  dateModalAction: {
    minWidth: 48,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  dateModalActionPressed: {
    opacity: 0.55,
  },
  dateModalCancel: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: "#6B706A",
  },
  dateModalConfirm: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#FF7B32",
  },
  iosDatePicker: {
    width: "100%",
  },
  submitButton: {
    width: "100%",
    height: 58,
    minHeight: 58,
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    textAlign: "center",
  },
  loginLink: {
    alignSelf: "center",
    marginTop: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
  },
  loginLinkPressed: {
    opacity: 0.55,
  },
  loginText: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#706864",
    textAlign: "center",
    writingDirection: "rtl",
  },
  loginHighlight: {
    fontFamily: FONTS.medium,
    color: "#FF7B32",
  },
});
