import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

export const registrationSuccessStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9F8FB",
  },
  scrollView: {
    flex: 1,
    width: "100%",
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    paddingTop: 12,
    paddingBottom: 28,
  },
  content: {
    alignSelf: "center",
  },
  brandRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginBottom: 16,
  },
  brandText: {
    fontFamily: FONTS.bold,
    fontSize: 25,
    color: "#20201F",
  },
  brandAccent: {
    fontFamily: FONTS.bold,
    fontSize: 25,
    color: "#FF8142",
  },
  heroCard: {
    position: "relative",
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 21,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#EEE7E2",
    backgroundColor: "#FFFFFF",
  },
  heroDecorationOne: {
    position: "absolute",
    top: -45,
    right: -35,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "#FFF1E8",
  },
  heroDecorationTwo: {
    position: "absolute",
    bottom: -55,
    left: -45,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "#ECF6EE",
  },
  heroIconHalo: {
    position: "relative",
    width: 102,
    height: 102,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 51,
    backgroundColor: "#FFF4EC",
  },
  heroIconCircle: {
    width: 74,
    height: 74,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 37,
    borderWidth: 1,
    borderColor: "#F1C7AA",
    backgroundColor: "#FFFFFF",
  },
  heroCheck: {
    position: "absolute",
    right: 2,
    bottom: 7,
    width: 29,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    borderWidth: 3,
    borderColor: "#FFF4EC",
    backgroundColor: "#16833A",
  },
  rolePill: {
    marginTop: 13,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#FFF0E6",
  },
  rolePillText: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: "#A6521D",
    textAlign: "center",
  },
  title: {
    marginTop: 12,
    fontFamily: FONTS.bold,
    fontSize: 25,
    lineHeight: 35,
    color: "#24201E",
    textAlign: "center",
    writingDirection: "rtl",
  },
  description: {
    maxWidth: 430,
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: 14,
    lineHeight: 23,
    color: "#6D6560",
    textAlign: "center",
    writingDirection: "rtl",
  },
  statusCard: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    marginTop: 14,
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 17,
    borderWidth: 1,
  },
  activeStatusCard: {
    borderColor: "#C9DECD",
    backgroundColor: "#F3F9F4",
  },
  pendingStatusCard: {
    borderColor: "#EACDB8",
    backgroundColor: "#FFF7F1",
  },
  statusIcon: {
    width: 47,
    height: 47,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
  },
  activeStatusIcon: {
    backgroundColor: "#E2F1E5",
  },
  pendingStatusIcon: {
    backgroundColor: "#FFE8D7",
  },
  statusTextContainer: {
    flex: 1,
  },
  statusTitleRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusLabel: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#746E69",
    textAlign: "left",
    writingDirection: "rtl",
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  activeStatusDot: {
    backgroundColor: "#16833A",
  },
  pendingStatusDot: {
    backgroundColor: "#C36A29",
  },
  statusTitle: {
    marginTop: 3,
    fontFamily: FONTS.bold,
    fontSize: 16,
    textAlign: "left",
    writingDirection: "rtl",
  },
  activeStatusTitle: {
    color: "#176F32",
  },
  pendingStatusTitle: {
    color: "#A9571C",
  },
  statusDescription: {
    marginTop: 2,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#6A6662",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionHeader: {
    width: "100%",
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: 21,
    color: "#292522",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionDescription: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 19,
    color: "#746D68",
    textAlign: "left",
    writingDirection: "rtl",
  },
  capabilitiesCard: {
    width: "100%",
    overflow: "hidden",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E4E7E3",
    backgroundColor: "#FFFFFF",
  },
  capabilityRow: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    paddingHorizontal: 15,
    paddingVertical: 14,
  },
  capabilityRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E8EAE7",
  },
  capabilityCheck: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    borderRadius: 13,
    backgroundColor: "#16833A",
  },
  capabilityTextContainer: {
    flex: 1,
  },
  capabilityTitleRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  capabilityTitle: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#2D2926",
    textAlign: "left",
    writingDirection: "rtl",
  },
  capabilityDescription: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#746F6B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  profileCard: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D8D0C8",
    backgroundColor: "#FAF8F5",
  },
  profileIcon: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: "#FFFFFF",
  },
  profileTextContainer: {
    flex: 1,
  },
  profileTitle: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#34302D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  profileDescription: {
    marginTop: 2,
    fontFamily: FONTS.regular,
    fontSize: 10.5,
    color: "#77716C",
    textAlign: "left",
    writingDirection: "rtl",
  },
  progressContainer: {
    alignItems: "center",
    gap: 5,
  },
  progressText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: "#177234",
  },
  progressTrack: {
    width: 56,
    height: 6,
    overflow: "hidden",
    borderRadius: 3,
    backgroundColor: "#E5E5E2",
  },
  progressFill: {
    width: "60%",
    height: "100%",
    borderRadius: 3,
    backgroundColor: "#177234",
  },
  primaryButton: {
    width: "100%",
    minHeight: 57,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 22,
    borderRadius: 17,
    backgroundColor: "#FF8849",
  },
  primaryButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  primaryButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#FFFFFF",
    textAlign: "center",
  },
  secondaryButton: {
    width: "100%",
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: "#687866",
    backgroundColor: "#FFFFFF",
  },
  secondaryButtonPressed: {
    opacity: 0.65,
  },
  secondaryButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: "#176F32",
    textAlign: "center",
  },
});
