import { StyleSheet } from "react-native";
import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FBFAFE" },
  keyboardView: { flex: 1 },
  screen: { flex: 1, backgroundColor: "#FBFAFE" },
  topBar: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 20,
    color: "#24201E",
    textAlign: "center",
    writingDirection: "rtl",
  },
  topBarSpacer: { width: 46, height: 46 },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: "#EFEFF1",
  },
  backButtonPressed: { opacity: 0.65, transform: [{ scale: 0.94 }] },
  progressArea: { paddingTop: 4, paddingBottom: 18 },
  progressLabels: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressTitle: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#5D5551",
    textAlign: "left",
    writingDirection: "rtl",
  },
  stepText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#FF7B32",
    textAlign: "left",
    writingDirection: "rtl",
  },
  progressTrack: {
    width: "100%",
    height: 5,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#E4E1DF",
  },
  progressFill: {
    width: "66.666%",
    height: "100%",
    alignSelf: "flex-end",
    borderRadius: 999,
    backgroundColor: "#FF8849",
  },
  scrollView: { flex: 1 },
  scrollContent: { alignItems: "center", paddingBottom: 38 },
  content: { alignSelf: "center" },
  formErrorSummary: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#E7AAB2",
    backgroundColor: "#FFF1F3",
  },
  formErrorSummaryTextWrap: {
    flex: 1,
  },
  formErrorSummaryTitle: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#A51F32",
    textAlign: "left",
    writingDirection: "rtl",
  },
  formErrorSummaryText: {
    marginTop: 3,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 19,
    color: "#7F3944",
    textAlign: "left",
    writingDirection: "rtl",
  },
  reviewCard: {
    width: "100%",
    marginBottom: 22,
    paddingHorizontal: 17,
    paddingVertical: 16,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#F1C9AA",
    backgroundColor: "#FFF4EB",
  },
  reviewHeader: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 8,
    marginBottom: 7,
  },
  reviewTitle: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: "#A7551E",
    textAlign: "left",
    writingDirection: "rtl",
  },
  reviewText: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    lineHeight: 22,
    color: "#7B4B2B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionHeader: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 9,
    marginBottom: 18,
  },
  spacedHeader: { marginTop: 25 },
  sectionMarker: {
    width: 4,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#16833A",
  },
  sectionTitle: {
    fontFamily: FONTS.medium,
    fontSize: 17,
    color: "#16833A",
    textAlign: "left",
    writingDirection: "rtl",
  },
  fieldGroup: { width: "100%", marginBottom: 16, marginTop: 16 },
  inputContainer: {
    width: "100%",
    minHeight: 57,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#7E897D",
    backgroundColor: "#FBFAFE",
  },
  inputContainerError: { borderColor: "#C92335" },
  pressedField: { opacity: 0.72 },
  input: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: "#2F332F",
    writingDirection: "rtl",
  },
  selectText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 15,
    color: "#2F332F",
    textAlign: "left",
    writingDirection: "rtl",
  },
  selectPlaceholder: { color: "#777B75" },
  phoneRow: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  phoneInputContainer: { flex: 1, width: undefined },
  countryCodeBox: {
    width: 72,
    minHeight: 57,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#A4ADA2",
    backgroundColor: "#F1F2EE",
  },
  countryCodeText: { fontFamily: FONTS.medium, fontSize: 15, color: "#687067" },
  textAreaContainer: {
    width: "100%",
    minHeight: 118,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#7E897D",
    backgroundColor: "#FBFAFE",
  },
  textArea: {
    flex: 1,
    minHeight: 92,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: 14,
    lineHeight: 22,
    color: "#2F332F",
    writingDirection: "rtl",
  },
  counterText: {
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: "#7D837D",
    textAlign: "left",
  },
  dropdown: {
    width: "100%",
    height: 240,
    overflow: "hidden",
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D6D9D4",
    backgroundColor: "#FFFFFF",
  },
  dropdownContent: { flexGrow: 0 },
  dropdownItem: {
    minHeight: 48,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#ECEDEB",
  },
  selectedDropdownItem: { backgroundColor: "#F1F8F3" },
  dropdownItemPressed: { opacity: 0.66 },
  dropdownItemText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: "#333833",
    textAlign: "left",
    writingDirection: "rtl",
  },
  mapCard: {
    width: "100%",
    height: 190,
    overflow: "hidden",
    marginTop: 2,
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D7DDD4",
    backgroundColor: "#E9EEE8",
  },
  mapCardError: {
    borderColor: "#C92335",
  },
  mapPreview: {
    width: "100%",
    height: "100%",
  },
  mapEmptyState: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: "rgba(233, 238, 232, 0.9)",
  },
  mapEmptyText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#697169",
    textAlign: "center",
    writingDirection: "rtl",
  },
  locationButton: {
    position: "absolute",
    left: 12,
    bottom: 12,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D8DDD6",
  },
  locationButtonPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  locationButtonText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#4E5B50",
    writingDirection: "rtl",
  },
  coordinateText: {
    width: "100%",
    marginBottom: 7,
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#5F675F",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helperText: {
    width: "100%",
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#6E756E",
    textAlign: "left",
    writingDirection: "rtl",
  },
  subLabel: {
    width: "100%",
    marginBottom: 11,
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: "#343934",
    textAlign: "left",
    writingDirection: "rtl",
  },
  subLabelSpacing: { marginTop: 17 },
  choiceWrap: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  choiceChip: {
    minHeight: 38,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#727A73",
    backgroundColor: "#FFFFFF",
  },
  selectedChoiceChip: { borderColor: "#FF8849", backgroundColor: "#FF8849" },
  choiceText: { fontFamily: FONTS.regular, fontSize: 13, color: "#4A504A" },
  selectedChoiceText: { color: "#FFFFFF" },
  switchCard: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: "#F5F4F0",
  },
  switchTextWrap: { flex: 1 },
  switchTitle: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#333933",
    textAlign: "left",
    writingDirection: "rtl",
  },
  switchSubtitle: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#737973",
    textAlign: "left",
    writingDirection: "rtl",
  },
  logoUploadCard: {
    width: "100%",
    minHeight: 125,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 13,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#B8C9B5",
    backgroundColor: "#FBFAFE",
  },
  logoPreview: { width: 58, height: 58, marginBottom: 8, borderRadius: 12 },
  logoUploadTitle: {
    marginTop: 5,
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: "#353A35",
    textAlign: "center",
    writingDirection: "rtl",
  },
  uploadCard: {
    width: "100%",
    minHeight: 78,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 13,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#CDD4CA",
    backgroundColor: "#FFFFFF",
  },
  uploadCardError: { borderColor: "#C92335" },
  uploadPreview: { width: 44, height: 44, borderRadius: 9 },
  uploadTextWrap: { flex: 1 },
  uploadTitle: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#353A35",
    textAlign: "left",
    writingDirection: "rtl",
  },
  uploadSubtitle: {
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: 10,
    lineHeight: 16,
    color: "#828982",
    textAlign: "left",
    writingDirection: "rtl",
  },
  uploadButton: {
    flexShrink: 0,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#FF8849",
    backgroundColor: "#FFF5EE",
  },
  uploadButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: "#FF7B32",
  },
  passwordStrengthHeader: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: -2,
    marginBottom: 7,
  },
  passwordStrengthTitle: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#5B615B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  passwordStrengthLabel: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    textAlign: "left",
    writingDirection: "rtl",
  },
  passwordBars: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    gap: 6,
    marginBottom: 15,
  },
  passwordBar: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#E1E1DE",
  },
  requirements: {
    width: "100%",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 22,
  },
  requirementRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  requirementText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#575D57",
    textAlign: "left",
    writingDirection: "rtl",
  },
  confirmationCard: {
    width: "100%",
    marginTop: 5,
    paddingHorizontal: 14,
    paddingTop: 15,
    paddingBottom: 4,
    borderRadius: 12,
    backgroundColor: "#F8F7F3",
  },
  checkboxRow: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 15,
  },
  checkbox: {
    width: 20,
    height: 20,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#C7CEC5",
    backgroundColor: "#FFFFFF",
  },
  checkboxSelected: { borderColor: "#16833A", backgroundColor: "#16833A" },
  checkboxText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#555B55",
    textAlign: "left",
    writingDirection: "rtl",
  },
  linkText: {
    fontFamily: FONTS.medium,
    color: "#16833A",
    textDecorationLine: "underline",
  },
  errorText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 18,
    color: "#C92335",
    textAlign: "left",
    writingDirection: "rtl",
  },
  submitButton: { width: "100%", height: 58, minHeight: 58, marginTop: 20 },
  submitHelperText: {
    marginTop: 8,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#7A6B63",
    textAlign: "center",
    writingDirection: "rtl",
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    textAlign: "center",
  },
  loginLink: {
    alignSelf: "center",
    marginTop: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
  },
  loginLinkPressed: { opacity: 0.55 },
  loginText: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#706864",
    textAlign: "center",
    writingDirection: "rtl",
  },
  loginHighlight: { fontFamily: FONTS.medium, color: "#FF7B32" },
  mapModalSafeArea: {
    flex: 1,
    backgroundColor: "#FBFAFE",
  },
  mapModalHeader: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#DDDCD9",
  },
  mapModalHeaderButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: "#EFEFF1",
  },
  mapModalHeaderButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  mapModalTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#24201E",
    textAlign: "center",
    writingDirection: "rtl",
  },
  mapModalHeaderSpacer: {
    width: 46,
    height: 46,
  },
  mapPickerWrap: {
    flex: 1,
  },
  mapPicker: {
    ...StyleSheet.absoluteFillObject,
  },
  mapInstructionCard: {
    position: "absolute",
    top: 14,
    left: 14,
    right: 14,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F1C9AA",
    backgroundColor: "rgba(255, 244, 235, 0.96)",
  },
  mapInstructionText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 19,
    color: "#7B4B2B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  currentLocationButton: {
    position: "absolute",
    right: 14,
    bottom: 18,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#BDD2C1",
    backgroundColor: "#FFFFFF",
  },
  currentLocationButtonPressed: {
    opacity: 0.72,
  },
  currentLocationButtonDisabled: {
    opacity: 0.55,
  },
  currentLocationButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#16833A",
    writingDirection: "rtl",
  },
  mapModalFooter: {
    paddingHorizontal: 17,
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#DDDCD9",
    backgroundColor: "#FBFAFE",
  },
  confirmLocationButton: {
    width: "100%",
    minHeight: 56,
  },
  dateModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    paddingBottom: 24,
    backgroundColor: "rgba(0, 0, 0, 0.34)",
  },
  dateModalCard: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
  },
  dateModalHeader: {
    minHeight: 54,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E5E5E5",
  },
  dateModalTitle: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#292D29",
    textAlign: "center",
    writingDirection: "rtl",
  },
  dateModalAction: {
    minWidth: 48,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  dateModalCancel: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: "#6B706A",
  },
  dateModalConfirm: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#FF7B32",
  },
  iosDatePicker: { width: "100%" },
});
