import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FBFAFE",
  },
  keyboardView: {
    flex: 1,
  },
  screen: {
    flex: 1,
    width: "100%",
    backgroundColor: "#FBFAFE",
  },
  scrollView: {
    flex: 1,
    width: "100%",
  },
  topGlow: {
    position: "absolute",
    backgroundColor: "#FFE1D2",
  },
  bottomGlow: {
    position: "absolute",
    backgroundColor: "#DDEFE2",
  },
  topBar: {
    width: "100%",
    minHeight: 58,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  topBarSpacer: {
    width: 46,
    height: 46,
  },
  backButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
    backgroundColor: "#EFEFF1",
  },
  backButtonPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.94 }],
  },
  scrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
  },
  content: {
    flexGrow: 1,
    alignSelf: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  illustrationContainer: {
    position: "relative",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  illustrationHalo: {
    position: "absolute",
    backgroundColor: "#FFF3ED",
  },
  phoneCard: {
    alignItems: "center",
    paddingTop: 7,
    paddingHorizontal: 6,
    paddingBottom: 7,
    backgroundColor: "#FFD8A6",
    borderWidth: 1.5,
    borderColor: "#75411F",
    shadowColor: "#8C512D",
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  phoneSpeaker: {
    width: 20,
    height: 3,
    borderRadius: 2,
    backgroundColor: "#875035",
    marginBottom: 6,
  },
  phoneScreen: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    backgroundColor: "#FFF4E6",
    borderWidth: 1,
    borderColor: "#E6A66A",
  },
  screenKey: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  phoneHomeIndicator: {
    width: 18,
    height: 3,
    marginTop: 6,
    borderRadius: 2,
    backgroundColor: "#8B5435",
  },
  codeBubble: {
    position: "absolute",
    right: "15%",
    top: "36%",
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#FFC677",
    borderWidth: 1.5,
    borderColor: "#75411F",
  },
  sparkleOne: {
    position: "absolute",
    left: "12%",
    top: "22%",
  },
  header: {
    width: "100%",
    alignItems: "center",
    marginBottom: 24,
  },
  title: {
    fontFamily: FONTS.bold,
    color: "#232323",
    textAlign: "center",
  },
  description: {
    maxWidth: 390,
    marginTop: 7,
    fontFamily: FONTS.regular,
    color: "#72645D",
    textAlign: "center",
  },
  form: {
    width: "100%",
  },
  phoneInfoCard: {
    width: "100%",
    minHeight: 72,
    flexDirection: "row-reverse",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E9BDA8",
  },
  phoneInfoIcon: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#FFE2D5",
  },
  phoneNumber: {
    flex: 1,
    marginHorizontal: 10,
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#302925",
    textAlign: "center",
    writingDirection: "ltr",
  },
  changePhoneButton: {
    minWidth: 48,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  changePhoneText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#AC4B18",
    textAlign: "center",
  },
  codeBoxes: {
    position: "relative",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    marginBottom: 16,
  },
  codeBox: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1.25,
    borderColor: "#E8BDAA",
  },
  filledCodeBox: {
    borderColor: "#DF8555",
    backgroundColor: "#FFF9F6",
  },
  activeCodeBox: {
    borderWidth: 1.8,
    borderColor: "#FF8849",
  },
  successCodeBox: {
    borderWidth: 2,
    borderColor: "#13853A",
    backgroundColor: "#F1FBF4",
  },
  errorCodeBox: {
    borderWidth: 2,
    borderColor: "#C95330",
    backgroundColor: "#FFF3EF",
  },
  codeDigit: {
    fontFamily: FONTS.bold,
    color: "#332B27",
    textAlign: "center",
  },
  hiddenCodeInput: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
  },
  successMessage: {
    width: "100%",
    minHeight: 30,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginBottom: 12,
  },
  successMessageText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    lineHeight: 20,
    color: "#13853A",
    textAlign: "center",
  },
  codeError: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 7,
    marginBottom: 12,
  },
  codeErrorText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#A53F20",
    textAlign: "right",
  },
  generalError: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: 13,
    backgroundColor: "#FFF0EA",
    borderWidth: 1,
    borderColor: "#F3C5B5",
  },
  generalErrorText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#9D3A20",
    textAlign: "right",
  },
  verifyButton: {
    direction: "ltr",
    width: "100%",
    marginTop: 10,
    paddingVertical: 0,
    shadowColor: "#E66F30",
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.18,
    shadowRadius: 13,
    elevation: 6,
  },
  verifyButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 16,
    color: "#603016",
    textAlign: "center",
  },
  disabledButtonText: {
    color: "#FFFFFF",
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 25,
  },
  resendQuestion: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#665852",
    textAlign: "center",
  },
  resendTimer: {
    marginTop: 7,
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#B75017",
    textAlign: "center",
  },
  resendButton: {
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  resendButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#B75017",
    textAlign: "center",
  },
  helpMessage: {
    maxWidth: 360,
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 6,
    marginTop: 18,
    paddingHorizontal: 12,
  },
  helpMessageText: {
    flexShrink: 1,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#258442",
    textAlign: "center",
  },
  linkPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.96 }],
  },
});

export default styles;
