import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  screen: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  topBar: {
    minHeight: 60,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E4E1DF",
    backgroundColor: "#F9F8FC",
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  topBarTitleWrap: {
    flex: 1,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  topBarTitle: {
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#282321",
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 30,
  },
  content: {
    direction: "rtl",
    alignSelf: "center",
    alignItems: "stretch",
  },
  hero: {
    width: "100%",
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 8,
  },
  logoBox: {
    width: 82,
    height: 82,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    backgroundColor: "#FF7E3D",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  brandRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  brandName: {
    fontFamily: FONTS.bold,
    fontSize: 25,
    color: "#2D2825",
  },
  brandAccent: {
    fontFamily: FONTS.bold,
    fontSize: 25,
    color: "#FF7E3D",
    marginStart: 1,
    marginEnd: 4,
  },
  tagline: {
    width: "100%",
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#756D68",
    textAlign: "center",
    writingDirection: "rtl",
  },
  versionPill: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#FFE2D2",
  },
  versionText: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: "#9A4C22",
    textAlign: "center",
    writingDirection: "rtl",
  },
  statementCard: {
    width: "100%",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFFFFF",
  },
  statementHeader: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statementTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: "#18833B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  visionTitle: {
    color: "#B64E00",
  },
  statementText: {
    width: "100%",
    marginTop: 10,
    fontFamily: FONTS.regular,
    fontSize: 12.5,
    lineHeight: 23,
    color: "#4F4844",
    textAlign: "left",
    writingDirection: "rtl",
  },
  featuresCard: {
    width: "100%",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFFFFF",
  },
  cardTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  featuresGrid: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 16,
    rowGap: 18,
  },
  featureItem: {
    width: "50%",
    alignItems: "center",
  },
  featureIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "#E7F4EA",
  },
  featureTitle: {
    marginTop: 7,
    fontFamily: FONTS.medium,
    fontSize: 11.5,
    color: "#3D3733",
    textAlign: "center",
    writingDirection: "rtl",
  },
  infoCard: {
    overflow: "hidden",
    width: "100%",
    marginTop: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E4E1DF",
    backgroundColor: "#FFFFFF",
  },
  infoHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  infoRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  infoLabel: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#776F69",
    textAlign: "left",
    writingDirection: "rtl",
  },
  infoValue: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#3E3834",
  },
  rowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E7E4E2",
  },
  licensesCard: {
    width: "100%",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFFFFF",
  },
  licensesTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  licensesDescription: {
    width: "100%",
    marginTop: 8,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 21,
    color: "#5B534E",
    textAlign: "left",
    writingDirection: "rtl",
  },
  licensesButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#B6BDB7",
    backgroundColor: "#FFFFFF",
  },
  licensesButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#18833B",
    textAlign: "center",
    writingDirection: "rtl",
  },
  socialCard: {
    overflow: "hidden",
    width: "100%",
    marginTop: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E4E1DF",
    backgroundColor: "#FFFFFF",
  },
  socialTitle: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: "#B64E00",
    textAlign: "left",
    writingDirection: "rtl",
    backgroundColor: "#FFF7F2",
  },
  socialRow: {
    minHeight: 52,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
  },
  socialText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12.5,
    color: "#3E3834",
    textAlign: "left",
    writingDirection: "rtl",
  },
  rowPressed: {
    backgroundColor: "#F6F5F4",
  },
  helpCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#FF7E3D",
    backgroundColor: "#FFF5EF",
  },
  helpTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#B6531D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#7E6D65",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpButton: {
    alignSelf: "flex-start",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 7,
  },
  helpButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#AD4B18",
    textAlign: "right",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  shareCard: {
    width: "100%",
    alignItems: "stretch",
    marginTop: 18,
    paddingHorizontal: 18,
    paddingVertical: 19,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFF7F2",
  },
  shareTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 17,
    color: "#B64E00",
    textAlign: "left",
    writingDirection: "rtl",
  },
  shareDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 11.5,
    lineHeight: 19,
    color: "#765E50",
    textAlign: "left",
    writingDirection: "rtl",
  },
  shareButton: {
    alignSelf: "flex-start",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginTop: 13,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
  },
  shareButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 12.5,
    color: "#B64E00",
    writingDirection: "rtl",
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 30,
    paddingBottom: 10,
  },
  footerLine: {
    width: 72,
    height: 1,
    backgroundColor: "#D7D4D1",
  },
  footerCopyright: {
    marginTop: 16,
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#8A827D",
    textAlign: "center",
    writingDirection: "rtl",
  },
  footerLinks: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 12,
  },
  footerLink: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: "#18833B",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  footerDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: "#AAA29D",
  },
  footerContact: {
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  footerContactText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#7B736E",
    textDecorationLine: "underline",
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: "rgba(36, 31, 28, 0.42)",
  },
  modalCard: {
    direction: "rtl",
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F1EFED",
  },
  modalTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  modalText: {
    width: "100%",
    marginTop: 14,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 21,
    color: "#5B534E",
    textAlign: "left",
    writingDirection: "rtl",
  },
  licenseList: {
    marginTop: 14,
    gap: 9,
  },
  licenseItem: {
    width: "100%",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 9,
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#3F3935",
    textAlign: "left",
    backgroundColor: "#F8F7F6",
  },
  modalDoneButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
    borderRadius: 12,
    backgroundColor: "#B64E00",
  },
  modalDoneText: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#FFFFFF",
    writingDirection: "rtl",
  },
  pressed: {
    opacity: 0.65,
    transform: [{ scale: 0.98 }],
  },
});
