import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  screen: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  topBar: {
    minHeight: 60,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E4E1DF",
    backgroundColor: "#F9F8FC",
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 19,
    color: "#282321",
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 34,
  },
  content: {
    width: "100%",
    direction: "rtl",
    alignSelf: "center",
    alignItems: "stretch",
  },
  heroImage: {
    width: "100%",
    height: 186,
    borderRadius: 15,
    backgroundColor: "#FFE4D4",
  },
  heroTextWrap: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
  },
  heroTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 27,
    lineHeight: 38,
    color: "#292421",
    textAlign: "left",
    writingDirection: "rtl",
  },
  heroDescription: {
    width: "100%",
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: 13,
    lineHeight: 23,
    color: "#645B56",
    textAlign: "left",
    writingDirection: "rtl",
  },
  formCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 24,
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFFFFF",
  },
  fieldGroup: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginBottom: 18,
  },
  fieldGroupLast: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
  },
  label: {
    width: "100%",
    marginBottom: 7,
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#544B46",
    textAlign: "left",
    writingDirection: "rtl",
  },
  input: {
    width: "100%",
    minHeight: 54,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CDB7AA",
    backgroundColor: "#FFFFFF",
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#332E2B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  ltrInput: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  selectInput: {
    direction: "rtl",
    width: "100%",
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CDB7AA",
    backgroundColor: "#FFFFFF",
  },
  selectText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#332E2B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  selectPlaceholder: {
    color: "#99918B",
  },
  messageLabelRow: {
    direction: "rtl",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  counterText: {
    fontFamily: FONTS.regular,
    fontSize: 10.5,
    color: "#8F847E",
    textAlign: "left",
    writingDirection: "ltr",
  },
  counterError: {
    color: "#C73732",
  },
  messageInput: {
    width: "100%",
    minHeight: 132,
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CDB7AA",
    backgroundColor: "#FFFFFF",
    fontFamily: FONTS.regular,
    fontSize: 13,
    lineHeight: 22,
    color: "#332E2B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  inputError: {
    borderColor: "#D9544F",
    backgroundColor: "#FFF9F8",
  },
  errorText: {
    width: "100%",
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#C73732",
    textAlign: "left",
    writingDirection: "rtl",
  },
  uploadBox: {
    width: "100%",
    minHeight: 122,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#E8BCA5",
    backgroundColor: "#FAF9FB",
  },
  uploadTitle: {
    marginTop: 7,
    fontFamily: FONTS.medium,
    fontSize: 12.5,
    color: "#5D5550",
    textAlign: "center",
    writingDirection: "rtl",
  },
  uploadHint: {
    marginTop: 3,
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: "#8B817B",
    textAlign: "center",
    writingDirection: "ltr",
  },
  attachmentPreview: {
    width: "100%",
    height: 160,
  },
  removeAttachmentButton: {
    direction: "rtl",
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingVertical: 5,
  },
  removeAttachmentText: {
    fontFamily: FONTS.medium,
    fontSize: 11.5,
    color: "#C73732",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#FF7E3D",
    backgroundColor: "#FFF5EF",
  },
  helpTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#B6531D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#7E6D65",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpButton: {
    direction: "rtl",
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 7,
  },
  helpButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#AD4B18",
    textAlign: "left",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  contactInfoCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E4E1DF",
    backgroundColor: "#FFFFFF",
  },
  sectionTitle: {
    width: "100%",
    marginBottom: 12,
    fontFamily: FONTS.bold,
    fontSize: 17,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contactInfoRow: {
    direction: "rtl",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
    paddingVertical: 10,
  },
  contactTextWrap: {
    flex: 1,
    direction: "rtl",
    alignItems: "stretch",
  },
  contactLabel: {
    width: "100%",
    fontFamily: FONTS.regular,
    fontSize: 10.5,
    color: "#7D736D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contactValue: {
    width: "100%",
    marginTop: 2,
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#3C3632",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contactValueLTR: {
    width: "100%",
    marginTop: 2,
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#3C3632",
    textAlign: "left",
    writingDirection: "ltr",
  },
  contactIconOrange: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "#FFF0E7",
  },
  contactIconGreen: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "#E7F4EA",
  },
  contactIconNeutral: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "#EFEEED",
  },
  socialCard: {
    width: "100%",
    direction: "rtl",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E4E1DF",
    backgroundColor: "#FFFFFF",
  },
  socialGrid: {
    direction: "rtl",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  socialItem: {
    width: "24%",
    alignItems: "center",
  },
  socialIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "#EFEEED",
  },
  socialLabel: {
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: 10.5,
    color: "#5D5550",
    textAlign: "center",
    writingDirection: "rtl",
  },
  submitButton: {
    direction: "rtl",
    width: "100%",
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 24,
    borderRadius: 14,
    backgroundColor: "#B64E00",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  submitButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: "#FFFFFF",
    textAlign: "center",
    writingDirection: "rtl",
  },
  submitPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  submitDisabled: {
    opacity: 0.55,
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: "rgba(36, 31, 28, 0.42)",
  },
  typeModalCard: {
    overflow: "hidden",
    direction: "rtl",
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
  },
  modalHeader: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E4E1DF",
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F1EFED",
  },
  modalTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 17,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  typeOption: {
    minHeight: 52,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
    paddingHorizontal: 16,
  },
  typeOptionBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E7E4E2",
  },
  typeOptionText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#3E3834",
    textAlign: "left",
    writingDirection: "rtl",
  },
  rowPressed: {
    backgroundColor: "#F7F6F5",
  },
  fieldPressed: {
    opacity: 0.75,
  },
  pressed: {
    opacity: 0.65,
    transform: [{ scale: 0.98 }],
  },
});
