import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  screen: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  topBar: {
    minHeight: 60,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E4E1DF",
    backgroundColor: "#F9F8FC",
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 19,
    color: "#282321",
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 18,
  },
  content: {
    alignSelf: "center",
    direction: "rtl",
  },
  heroImage: {
    width: "100%",
    height: 176,
    borderRadius: 14,
    backgroundColor: "#FFE4CE",
  },
  heroTitle: {
    width: "100%",
    marginTop: 15,
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: "#3B3531",
    textAlign: "center",
    writingDirection: "rtl",
  },
  heroDescription: {
    width: "100%",
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#756D68",
    textAlign: "center",
    writingDirection: "rtl",
  },
  searchContainer: {
    width: "100%",
    minHeight: 52,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginTop: 20,
    paddingHorizontal: 17,
    borderRadius: 26,
    backgroundColor: "#ECEAE7",
  },
  searchInput: {
    flex: 1,
    paddingVertical: 0,
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#383330",
    textAlign: "right",
    writingDirection: "rtl",
  },
  categoriesGrid: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
    marginTop: 34,
  },
  categoryCard: {
    width: "48.3%",
    minHeight: 98,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#E2E4E2",
    backgroundColor: "#FFFFFF",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  categoryIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  categoryTitle: {
    marginTop: 8,
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#302B28",
    textAlign: "center",
    writingDirection: "rtl",
  },
  section: {
    width: "100%",
    marginTop: 28,
  },
  sectionTitle: {
    width: "100%",
    marginBottom: 12,
    fontFamily: FONTS.bold,
    fontSize: 21,
    color: "#282321",
    textAlign: "left",
    writingDirection: "rtl",
  },
  faqList: {
    gap: 10,
  },
  faqCard: {
    width: "100%",
    paddingHorizontal: 17,
    paddingVertical: 15,
    borderRadius: 13,
    backgroundColor: "#F4F1ED",
  },
  faqHeader: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  faqQuestion: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#332E2B",
    textAlign: "left",
    writingDirection: "rtl",
  },
  faqAnswer: {
    width: "100%",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#DDD8D3",
    fontFamily: FONTS.regular,
    fontSize: 12.5,
    lineHeight: 22,
    color: "#655C56",
    textAlign: "left",
    writingDirection: "rtl",
  },
  articlesCard: {
    overflow: "hidden",
    width: "100%",
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#E0E3E0",
    backgroundColor: "#FFFFFF",
  },
  articleRow: {
    minHeight: 72,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  articleBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E3E5E3",
  },
  articlePressed: {
    backgroundColor: "#F6F6F5",
  },
  articleIcon: {
    width: 43,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#EAF3ED",
  },
  articleTextWrap: {
    flex: 1,
  },
  articleTitle: {
    width: "100%",
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#302B28",
    textAlign: "left",
    writingDirection: "rtl",
  },
  articleMeta: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  articleDuration: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#68716B",
    writingDirection: "rtl",
  },
  supportCard: {
    width: "100%",
    alignItems: "stretch",
    marginTop: 32,
    paddingHorizontal: 20,
    paddingVertical: 22,
    borderRadius: 18,
    backgroundColor: "#FF8847",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  supportTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: "#FFFFFF",
    textAlign: "center",
    writingDirection: "rtl",
  },
  supportDescription: {
    width: "100%",
    marginTop: 7,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#FFF7F2",
    textAlign: "center",
    writingDirection: "rtl",
  },
  supportPrimaryButton: {
    minHeight: 46,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 18,
    borderRadius: 23,
    backgroundColor: "#A84D00",
  },
  supportPrimaryText: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#FFFFFF",
    writingDirection: "rtl",
  },
  supportSecondaryButton: {
    minHeight: 46,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 9,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: "#FFD3B8",
    backgroundColor: "#FF9A62",
  },
  supportSecondaryText: {
    fontFamily: FONTS.medium,
    fontSize: 14,
    color: "#FFFFFF",
    writingDirection: "rtl",
  },
  linksCard: {
    overflow: "hidden",
    width: "100%",
    marginTop: 28,
    borderRadius: 14,
    backgroundColor: "#EDEBE8",
  },
  linkRow: {
    minHeight: 54,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
  },
  linkText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: "#3A3532",
    textAlign: "left",
    writingDirection: "rtl",
  },
  linkDivider: {
    height: StyleSheet.hairlineWidth,
    marginHorizontal: 16,
    backgroundColor: "#D9D6D2",
  },
  linkPressed: {
    backgroundColor: "#E4E1DD",
  },
  footer: {
    width: "100%",
    alignItems: "center",
    marginTop: 40,
    paddingTop: 25,
    paddingBottom: 32,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#D8D5D2",
  },
  footerLogo: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: "#FF7438",
  },
  footerCopyright: {
    marginTop: 13,
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: "#6F6A66",
    textAlign: "center",
    writingDirection: "rtl",
  },
  footerLinks: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    marginTop: 12,
  },
  footerLink: {
    fontFamily: FONTS.regular,
    fontSize: 10.5,
    color: "#706A66",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  emptyCard: {
    width: "100%",
    alignItems: "center",
    marginTop: 28,
    paddingHorizontal: 20,
    paddingVertical: 25,
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
  },
  emptyTitle: {
    marginTop: 10,
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: "#38322F",
    textAlign: "center",
    writingDirection: "rtl",
  },
  emptyText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#716964",
    textAlign: "center",
    writingDirection: "rtl",
  },
  emptyButton: {
    marginTop: 15,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#B6530A",
  },
  emptyButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#FFFFFF",
    writingDirection: "rtl",
  },
  pressed: {
    opacity: 0.6,
  },
  cardPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
  supportPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.99 }],
  },
});
