import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  screen: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  topBar: {
    minHeight: 60,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E7E4E2",
    backgroundColor: "#F9F8FC",
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#24201E",
    textAlign: "center",
    writingDirection: "rtl",
  },
  topBarIconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  iconButtonPressed: {
    opacity: 0.55,
    transform: [{ scale: 0.94 }],
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 15,
    paddingBottom: 28,
  },
  content: {
    alignSelf: "center",
  },
  header: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 4,
    marginBottom: 18,
  },
  title: {
    fontFamily: FONTS.bold,
    fontSize: 26,
    lineHeight: 36,
    color: "#292421",
    textAlign: "center",
    writingDirection: "rtl",
  },
  updatedText: {
    marginTop: 4,
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: "#7C6E67",
    textAlign: "center",
    writingDirection: "rtl",
  },
  introText: {
    maxWidth: 520,
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: 13,
    lineHeight: 23,
    color: "#4D4642",
    textAlign: "center",
    writingDirection: "rtl",
  },
  summaryCard: {
    width: "100%",
    paddingHorizontal: 17,
    paddingVertical: 17,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#8EE59A",
    backgroundColor: "#D8F9DD",
  },
  summaryTitleRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 13,
  },
  summaryTitle: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: "#167C35",
    textAlign: "left",
    writingDirection: "rtl",
  },
  summaryList: {
    gap: 9,
  },
  summaryRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  summaryText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 19,
    color: "#24763A",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contentsCard: {
    width: "100%",
    overflow: "hidden",
    marginTop: 22,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E7BFA9",
    backgroundColor: "#F7F7FA",
  },
  contentsTitle: {
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: "#3D3733",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contentsRow: {
    minHeight: 46,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    backgroundColor: "#F7F7FA",
  },
  contentsRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E5E3E1",
  },
  contentsRowPressed: {
    backgroundColor: "#F0EFED",
  },
  contentsItemText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#4D4642",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionCard: {
    width: "100%",
    marginTop: 20,
    paddingHorizontal: 17,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFFFFF",
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: 20,
    lineHeight: 29,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionParagraph: {
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: 12.5,
    lineHeight: 23,
    color: "#4F4844",
    textAlign: "left",
    writingDirection: "rtl",
  },
  informationList: {
    marginTop: 13,
    gap: 15,
  },
  informationItem: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  informationIcon: {
    width: 28,
    alignItems: "center",
    paddingTop: 1,
  },
  informationTextWrap: {
    flex: 1,
  },
  informationTitle: {
    fontFamily: FONTS.medium,
    fontSize: 13,
    color: "#37312D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  informationDescription: {
    marginTop: 3,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 19,
    color: "#6B625D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  bulletList: {
    marginTop: 12,
    gap: 10,
  },
  bulletRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  bulletDot: {
    width: 5,
    height: 5,
    marginTop: 8,
    borderRadius: 3,
    backgroundColor: "#6F6762",
  },
  bulletText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 21,
    color: "#554E4A",
    textAlign: "left",
    writingDirection: "rtl",
  },
  promiseCard: {
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#43AEEA",
    backgroundColor: "#C8EAFD",
  },
  promiseText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    lineHeight: 21,
    color: "#19729D",
    textAlign: "center",
    writingDirection: "rtl",
  },
  protectionRow: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 13,
  },
  protectionIcon: {
    width: 58,
    height: 58,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 29,
    backgroundColor: "#A4F29A",
  },
  protectionText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 22,
    color: "#4E4844",
    textAlign: "left",
    writingDirection: "rtl",
  },
  rightsList: {
    marginTop: 14,
    gap: 9,
  },
  rightRow: {
    minHeight: 44,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: "#F8F7FA",
  },
  rightText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 19,
    color: "#514A46",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contactCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#FF7E3D",
    backgroundColor: "#FFF5EF",
  },
  contactTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#B6531D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contactDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#7E6D65",
    textAlign: "left",
    writingDirection: "rtl",
  },
  emailButton: {
    alignSelf: "flex-start",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 7,
  },
  emailButtonPressed: {
    opacity: 0.55,
  },
  emailText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#AD4B18",
    textAlign: "left",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  bottomBar: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E4E1DF",
    backgroundColor: "#FFFFFF",
  },
  bottomBarContent: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  shareBottomButton: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    backgroundColor: "#ECEBED",
  },
  contactButton: {
    flex: 1,
    minHeight: 50,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#B64E00",
  },
  contactButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: "#FFFFFF",
    textAlign: "center",
  },
  bottomButtonPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
});
