import { StyleSheet } from "react-native";

import { FONTS } from "@/src/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  screen: {
    flex: 1,
    backgroundColor: "#F9F8FC",
  },
  topBar: {
    minHeight: 60,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E4E1DF",
    backgroundColor: "#F9F8FC",
  },
  topBarButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  pressedButton: {
    opacity: 0.55,
    transform: [{ scale: 0.95 }],
  },
  topBarTitle: {
    flex: 1,
    fontFamily: FONTS.bold,
    fontSize: 19,
    color: "#282321",
    textAlign: "center",
    writingDirection: "rtl",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 15,
    paddingBottom: 28,
  },
  content: {
    direction: "rtl",
    alignSelf: "center",
    alignItems: "stretch",
  },
  header: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginBottom: 18,
  },
  title: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 27,
    lineHeight: 38,
    color: "#292421",
    textAlign: "left",
    writingDirection: "rtl",
  },
  updatedText: {
    width: "100%",
    marginTop: 4,
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: "#7C6E67",
    textAlign: "left",
    writingDirection: "rtl",
  },
  introText: {
    width: "100%",
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: 13,
    lineHeight: 23,
    color: "#4D4642",
    textAlign: "left",
    writingDirection: "rtl",
  },
  noticeCard: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 17,
    paddingVertical: 17,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#8EE59A",
    backgroundColor: "#D8F9DD",
  },
  noticeIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#11892D",
  },
  noticeTextWrap: {
    direction: "rtl",
    flex: 1,
    alignItems: "stretch",
  },
  noticeTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: "#167C35",
    textAlign: "left",
    writingDirection: "rtl",
  },
  noticeText: {
    width: "100%",
    marginTop: 4,
    fontFamily: FONTS.regular,
    fontSize: 12,
    lineHeight: 20,
    color: "#24763A",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contentsCard: {
    direction: "rtl",
    width: "100%",
    overflow: "hidden",
    marginTop: 22,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E7BFA9",
    backgroundColor: "#F7F7FA",
  },
  contentsTitle: {
    width: "100%",
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: "#3D3733",
    textAlign: "left",
    writingDirection: "rtl",
  },
  contentsRow: {
    minHeight: 46,
    alignItems: "stretch",
    justifyContent: "center",
    paddingHorizontal: 15,
    backgroundColor: "#F7F7FA",
  },
  contentsRowContent: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  contentsRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E5E3E1",
  },
  contentsRowPressed: {
    backgroundColor: "#F0EFED",
  },
  contentsItemText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: "#4D4642",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 17,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E9C5B2",
    backgroundColor: "#FFFFFF",
  },
  sectionTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 20,
    lineHeight: 29,
    color: "#2D2825",
    textAlign: "left",
    writingDirection: "rtl",
  },
  sectionParagraph: {
    width: "100%",
    marginTop: 12,
    fontFamily: FONTS.regular,
    fontSize: 12.5,
    lineHeight: 23,
    color: "#4F4844",
    textAlign: "left",
    writingDirection: "rtl",
  },
  warningCard: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 10,
    backgroundColor: "#FFF1EF",
  },
  warningText: {
    flex: 1,
    fontFamily: FONTS.medium,
    fontSize: 12,
    lineHeight: 21,
    color: "#C73732",
    textAlign: "left",
    writingDirection: "rtl",
  },
  bulletList: {
    width: "100%",
    marginTop: 14,
    gap: 11,
  },
  bulletRow: {
    width: "100%",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  bulletDot: {
    width: 6,
    height: 6,
    marginTop: 8,
    borderRadius: 3,
    backgroundColor: "#6D615A",
  },
  bulletText: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12.5,
    lineHeight: 22,
    color: "#554E4A",
    textAlign: "left",
    writingDirection: "rtl",
  },
  inlineContactButton: {
    alignSelf: "flex-end",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#FFF4EC",
  },
  inlineContactButtonPressed: {
    opacity: 0.6,
  },
  inlineContactText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#A84D16",
    textDecorationLine: "underline",
  },
  helpCard: {
    direction: "rtl",
    width: "100%",
    alignItems: "stretch",
    marginTop: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#FF7E3D",
    backgroundColor: "#FFF5EF",
  },
  helpTitle: {
    width: "100%",
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: "#B6531D",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpDescription: {
    width: "100%",
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 11,
    lineHeight: 18,
    color: "#7E6D65",
    textAlign: "left",
    writingDirection: "rtl",
  },
  helpLink: {
    alignSelf: "flex-start",
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 7,
  },
  helpLinkPressed: {
    opacity: 0.55,
  },
  helpText: {
    fontFamily: FONTS.medium,
    fontSize: 12,
    color: "#AD4B18",
    textAlign: "left",
    textDecorationLine: "underline",
    writingDirection: "rtl",
  },
  bottomBar: {
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E4E1DF",
    backgroundColor: "#FFFFFF",
  },
  bottomContent: {
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  shareButton: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    backgroundColor: "#ECEBED",
  },
  contactButton: {
    flex: 1,
    minHeight: 50,
    direction: "rtl",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: "#B64E00",
  },
  contactButtonText: {
    fontFamily: FONTS.medium,
    fontSize: 15,
    color: "#FFFFFF",
    textAlign: "center",
    writingDirection: "rtl",
  },
  bottomPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.99 }],
  },
});
